### ISSUE TITLE
Preprocessing Scripts

### ISSUE THREAD

**Issue by adebayoj** [neuromation/ml-recipe-bone-age#13]
Hi, 

Thank you for codebase; it is quite informative. I was wondering if you opensourced your preprocessing pipeline anywhere. I am working with the dataset and ran into some of the issues that you mentioned with the background, so I am looking to preprocess the dataset as well. Can you point me to this? 

Thanks!

**Comment by alexander-rakhlin** [comment]
Hi,
Unfortunately we don't have full preprocessing pipeline as it has been done in collaboration with other RSNA challenge participants some time ago and included radiograph segmentation and key points detection. Quite significant part of the overall project.

**Comment by adebayoj** [comment]
Sounds great; thanks for the quick response.
